# Generated by Django 3.1.5 on 2021-01-16 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('user', models.CharField(default='', editable=False, max_length=12, primary_key=True, serialize=False)),
                ('nome_funcionario', models.CharField(max_length=30)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='empresas.empresas')),
            ],
        ),
    ]
