# Generated by Django 3.1.5 on 2021-01-17 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresas',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionario', 'verbose_name_plural': 'Funcionarios'},
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='funcionarios', to='empresas.empresas'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='user',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
