# Generated by Django 3.1.5 on 2021-01-17 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20210116_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='user',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='EmpresasFuncionario',
            fields=[
                ('empresas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='empresas.empresas')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='empresas', to='empresas.funcionario')),
            ],
            bases=('empresas.empresas',),
        ),
    ]
