# Generated by Django 3.1.5 on 2021-01-17 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_auto_20210116_2307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmpresasFuncionario',
            new_name='EmpresasHeranca',
        ),
    ]
