# Generated by Django 3.1.5 on 2021-01-17 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_auto_20210117_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioEmpresaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='empresa_name', to='empresas.empresas')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_name', to='empresas.funcionario')),
            ],
        ),
        migrations.DeleteModel(
            name='EmpresasHeranca',
        ),
    ]
